package com.coditory.kttp.headers

import com.coditory.kttp.HttpSerializable
import java.nio.charset.Charset

data class MediaType(
    val type: String,
    val subtype: String,
    val parameters: HttpHeaderParams = HttpHeaderParams.empty(),
) : HttpSerializable {
    val value by lazy { "$type/$subtype" + parameters.toHttpString() }

    override fun toString() = toHttpString()

    override fun toHttpString(builder: Appendable) {
        builder.append(value)
    }

    fun fileExt(): String? {
        return getExtByMediaTypeValue(value)
    }

    fun quality(): Float? {
        return parameters["q"]?.toFloatOrNull()
    }

    fun withQuality(quality: Float?): MediaType {
        return if (quality() == quality) this else withoutParameter("q")
    }

    fun withParameter(name: String, value: String?): MediaType {
        if (value == null) return withoutParameter(name)
        if (parameters.contains(name, value)) return this
        return MediaType(type, subtype, parameters.with(name, value, overrideEntry = true))
    }

    private fun hasParameter(name: String, value: String): Boolean {
        return parameters.contains(name, value)
    }

    fun withoutParameter(name: String): MediaType {
        if (!parameters.contains(name)) return this
        return MediaType(type, subtype, parameters.without(name))
    }

    fun withoutParameter(name: String, value: String): MediaType {
        if (!parameters.contains(name, value)) return this
        return MediaType(type, subtype, parameters.without(name, value))
    }

    fun withoutParameters(): MediaType = when {
        parameters.isEmpty() -> this
        else -> MediaType(type, subtype)
    }

    fun withCharset(charset: Charset): MediaType = withParameter("charset", charset.name())

    fun charsetName(): String? {
        return parameters["charset"]
    }

    fun charset(): Charset? {
        val name = charsetName()
        return try {
            Charset.forName(name)
        } catch (_: IllegalArgumentException) {
            null
        }
    }

    fun contains(other: MediaType, ignoreParams: Boolean = false): Boolean {
        if (type != "*" && !type.equals(other.type, ignoreCase = true)) {
            return false
        }
        if (subtype != "*" && !subtype.equals(other.subtype, ignoreCase = true)) {
            if (!other.subtype.contains('+') || subtype.contains('+')) {
                return false
            }
            if (!other.subtype.endsWith("+$subtype", ignoreCase = true)) {
                return false
            }
        }
        if (ignoreParams) return true
        for ((paramName, paramValues) in parameters.toMap()) {
            val mediaParams = other.parameters.getAll(paramName)?.toSet() ?: emptySet()
            if (!mediaParams.containsAll(paramValues)) {
                return false
            }
        }
        return true
    }

    companion object {
        private val mediaTypeExtMapper by lazy { MimeTypeExtMapper() }
        private val cache = mutableMapOf<String, MediaType>()

        private fun mediaType(type: String, subtype: String): MediaType {
            return cache.getOrPut("$type/$subtype") { MediaType(type, subtype) }
        }

        fun parse(value: String): MediaType? {
            val cached = cache[value]
            if (cached != null) return cached
            val header = HttpHeaderValue.parse(value) ?: return null
            if (header.items.size != 1) throw BadMediaTypeFormatException(value)
            val item = header.items.first()
            return parse(item)
        }

        fun parse(item: HttpHeaderValueItem): MediaType? {
            if (item.params.isEmpty()) {
                val cached = cache[item.value]
                if (cached != null) return cached
            }
            val parts = item.value
            val slash = parts.indexOf('/')
            if (slash == -1) {
                throw BadMediaTypeFormatException(item.toHttpString())
            }
            val type = parts.substring(0, slash).trim()
            if (type.isEmpty()) {
                throw BadMediaTypeFormatException(item.toHttpString())
            }
            val subtype = parts.substring(slash + 1).trim()
            if (type.contains(' ') || subtype.contains(' ')) {
                throw BadMediaTypeFormatException(item.toHttpString())
            }
            if (subtype.isEmpty() || subtype.contains('/')) {
                throw BadMediaTypeFormatException(item.toHttpString())
            }
            if (item.params.isEmpty()) {
                val cached = cache["$type/$subtype"]
                if (cached != null) return cached
            }
            return MediaType(type, subtype, item.params)
        }

        fun minimize(contentTypes: Collection<MediaType>, ignoreParams: Boolean = false): Set<MediaType> {
            val result = mutableSetOf<MediaType>()
            val types = if (ignoreParams) {
                contentTypes.map { it.withoutParameters() }.toList()
            } else {
                contentTypes.toList()
            }
            for (i in 0 until contentTypes.size) {
                val ci = types[i]
                var skip = false
                for (j in i + 1 until contentTypes.size) {
                    val cj = types[j]
                    if (cj.contains(ci)) {
                        skip = true
                        break
                    }
                }
                if (!skip) {
                    result.add(ci)
                }
            }
            return result
        }

        fun getMediaTypeValueByExt(fileExt: CharSequence): String? {
            return mediaTypeExtMapper.getMimeTypeByExt(fileExt)
        }

        fun getMediaTypeByExt(fileExt: CharSequence): MediaType? {
            return getMediaTypeValueByExt(fileExt)
                ?.let { parse(it) }
        }

        fun getExtByMediaType(mediaType: MediaType): String? {
            return getExtByMediaTypeValue(mediaType.value)
        }

        fun getExtByMediaTypeValue(mimeType: CharSequence): String? {
            return mediaTypeExtMapper.getExtByMediaType(mimeType)
        }

        fun getAllFileExtByMediaType(mediaType: MediaType): List<String> {
            return getAllFileExtByMediaTypeValue(mediaType.value)
        }

        fun getAllFileExtByMediaTypeValue(mimeType: CharSequence): List<String> {
            return mediaTypeExtMapper.getAllFileExtByMediaType(mimeType)
        }
    }

    object Application {
        const val TYPE: String = "application"
        val Any: MediaType = mediaType(TYPE, "*")
        val Atom: MediaType = mediaType(TYPE, "atom+xml")
        val Cbor: MediaType = mediaType(TYPE, "cbor")
        val Json: MediaType = mediaType(TYPE, "json")
        val HalJson: MediaType = mediaType(TYPE, "hal+json")
        val JavaScript: MediaType = mediaType(TYPE, "javascript")
        val OctetStream: MediaType = mediaType(TYPE, "octet-stream")
        val Rss: MediaType = mediaType(TYPE, "rss+xml")
        val Soap: MediaType = mediaType(TYPE, "soap+xml")
        val Xml: MediaType = mediaType(TYPE, "xml")
        val Xml_Dtd: MediaType = mediaType(TYPE, "xml-dtd")
        val Yaml: MediaType = mediaType(TYPE, "yaml")
        val Zip: MediaType = mediaType(TYPE, "zip")
        val GZip: MediaType = mediaType(TYPE, "gzip")
        val FormUrlEncoded: MediaType = mediaType(TYPE, "x-www-form-urlencoded")
        val Pdf: MediaType = mediaType(TYPE, "pdf")
        val Xlsx: MediaType = mediaType(TYPE, "vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        val Docx: MediaType = mediaType(TYPE, "vnd.openxmlformats-officedocument.wordprocessingml.document")
        val Pptx: MediaType =
            mediaType(TYPE, "vnd.openxmlformats-officedocument.presentationml.presentation")
        val ProtoBuf: MediaType = mediaType(TYPE, "protobuf")
        val Wasm: MediaType = mediaType(TYPE, "wasm")
        val ProblemJson: MediaType = mediaType(TYPE, "problem+json")
        val ProblemXml: MediaType = mediaType(TYPE, "problem+xml")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentType: CharSequence): Boolean = contentType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Audio {
        const val TYPE: String = "audio"
        val Any: MediaType = mediaType(TYPE, "*")
        val MP4: MediaType = mediaType(TYPE, "mp4")
        val MPEG: MediaType = mediaType(TYPE, "mpeg")
        val OGG: MediaType = mediaType(TYPE, "ogg")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentType: CharSequence): Boolean = contentType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Image {
        const val TYPE: String = "image"
        val Any: MediaType = mediaType(TYPE, "*")
        val GIF: MediaType = mediaType(TYPE, "gif")
        val JPEG: MediaType = mediaType(TYPE, "jpeg")
        val PNG: MediaType = mediaType(TYPE, "png")
        val SVG: MediaType = mediaType(TYPE, "svg+xml")
        val XIcon: MediaType = mediaType(TYPE, "x-icon")

        operator fun contains(contentSubtype: String): Boolean = contentSubtype.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Message {
        const val TYPE: String = "message"
        val Any: MediaType = mediaType(TYPE, "*")
        val Http: MediaType = mediaType(TYPE, "http")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentSubtype: String): Boolean = contentSubtype.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object MultiPart {
        const val TYPE: String = "multipart"
        val Any: MediaType = mediaType(TYPE, "*")
        val Mixed: MediaType = mediaType(TYPE, "mixed")
        val Alternative: MediaType = mediaType(TYPE, "alternative")
        val Related: MediaType = mediaType(TYPE, "related")
        val FormData: MediaType = mediaType(TYPE, "form-data")
        val Signed: MediaType = mediaType(TYPE, "signed")
        val Encrypted: MediaType = mediaType(TYPE, "encrypted")
        val ByteRanges: MediaType = mediaType(TYPE, "byteranges")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentType: CharSequence): Boolean = contentType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Text {
        const val TYPE: String = "text"
        val Any: MediaType = mediaType(TYPE, "*")
        val Plain: MediaType = mediaType(TYPE, "plain")
        val CSS: MediaType = mediaType(TYPE, "css")
        val CSV: MediaType = mediaType(TYPE, "csv")
        val Html: MediaType = mediaType(TYPE, "html")
        val JavaScript: MediaType = mediaType(TYPE, "javascript")
        val VCard: MediaType = mediaType(TYPE, "vcard")
        val Xml: MediaType = mediaType(TYPE, "xml")
        val EventStream: MediaType = mediaType(TYPE, "event-stream")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentType: CharSequence): Boolean = contentType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Video {
        const val TYPE: String = "video"
        val Any: MediaType = mediaType(TYPE, "*")
        val MPEG: MediaType = mediaType(TYPE, "mpeg")
        val MP4: MediaType = mediaType(TYPE, "mp4")
        val OGG: MediaType = mediaType(TYPE, "ogg")
        val QuickTime: MediaType = mediaType(TYPE, "quicktime")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(contentType: CharSequence): Boolean = contentType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }

    object Font {
        const val TYPE: String = "font"
        val Any: MediaType = mediaType(TYPE, "*")
        val Collection: MediaType = mediaType(TYPE, "collection")
        val Otf: MediaType = mediaType(TYPE, "otf")
        val Sfnt: MediaType = mediaType(TYPE, "sfnt")
        val Ttf: MediaType = mediaType(TYPE, "ttf")
        val Woff: MediaType = mediaType(TYPE, "woff")
        val Woff2: MediaType = mediaType(TYPE, "woff2")

        fun subtype(subtype: String) = mediaType(TYPE, subtype)
        operator fun contains(mediaType: CharSequence): Boolean = mediaType.startsWith("$TYPE/", ignoreCase = true)
        operator fun contains(mediaType: MediaType): Boolean = mediaType.type.equals(TYPE, ignoreCase = true)
    }
}

class BadMediaTypeFormatException(value: String) : Exception("Bad Media-Type format: $value")

private class MimeTypeExtMapper {
    private val mimeTypeByExt = mutableMapOf<String, String>()
    private val extByMimeType = mutableMapOf<String, List<String>>()

    init {
        extByMimeType.put("application/andrew-inset", listOf("ez"))
        extByMimeType.put("application/applixware", listOf("aw"))
        extByMimeType.put("application/atom+xml", listOf("atom"))
        extByMimeType.put("application/atomcat+xml", listOf("atomcat"))
        extByMimeType.put("application/atomsvc+xml", listOf("atomsvc"))
        extByMimeType.put("application/ccxml+xml", listOf("ccxml"))
        extByMimeType.put("application/cdmi-capability", listOf("cdmia"))
        extByMimeType.put("application/cdmi-container", listOf("cdmic"))
        extByMimeType.put("application/cdmi-domain", listOf("cdmid"))
        extByMimeType.put("application/cdmi-object", listOf("cdmio"))
        extByMimeType.put("application/cdmi-queue", listOf("cdmiq"))
        extByMimeType.put("application/cu-seeme", listOf("cu"))
        extByMimeType.put("application/davmount+xml", listOf("davmount"))
        extByMimeType.put("application/docbook+xml", listOf("dbk"))
        extByMimeType.put("application/dssc+der", listOf("dssc"))
        extByMimeType.put("application/dssc+xml", listOf("xdssc"))
        extByMimeType.put("application/ecmascript", listOf("ecma"))
        extByMimeType.put("application/emma+xml", listOf("emma"))
        extByMimeType.put("application/epub+zip", listOf("epub"))
        extByMimeType.put("application/exi", listOf("exi"))
        extByMimeType.put("application/font-tdpfr", listOf("pfr"))
        extByMimeType.put("application/gml+xml", listOf("gml"))
        extByMimeType.put("application/gpx+xml", listOf("gpx"))
        extByMimeType.put("application/gxf", listOf("gxf"))
        extByMimeType.put("application/hyperstudio", listOf("stk"))
        extByMimeType.put("application/inkml+xml", listOf("ink", "inkml"))
        extByMimeType.put("application/ipfix", listOf("ipfix"))
        extByMimeType.put("application/java-archive", listOf("jar"))
        extByMimeType.put("application/java-serialized-object", listOf("ser"))
        extByMimeType.put("application/java-vm", listOf("class"))
        extByMimeType.put("application/javascript", listOf("js"))
        extByMimeType.put("application/json", listOf("json"))
        extByMimeType.put("application/jsonml+json", listOf("jsonml"))
        extByMimeType.put("application/lost+xml", listOf("lostxml"))
        extByMimeType.put("application/mac-binhex40", listOf("hqx"))
        extByMimeType.put("application/mac-compactpro", listOf("cpt"))
        extByMimeType.put("application/mads+xml", listOf("mads"))
        extByMimeType.put("application/marc", listOf("mrc"))
        extByMimeType.put("application/marcxml+xml", listOf("mrcx"))
        extByMimeType.put("application/mathematica", listOf("ma", "nb", "mb"))
        extByMimeType.put("application/mathml+xml", listOf("mathml"))
        extByMimeType.put("application/mbox", listOf("mbox"))
        extByMimeType.put("application/mediaservercontrol+xml", listOf("mscml"))
        extByMimeType.put("application/metalink+xml", listOf("metalink"))
        extByMimeType.put("application/metalink4+xml", listOf("meta4"))
        extByMimeType.put("application/mets+xml", listOf("mets"))
        extByMimeType.put("application/mods+xml", listOf("mods"))
        extByMimeType.put("application/mp21", listOf("m21", "mp21"))
        extByMimeType.put("application/mp4", listOf("mp4s"))
        extByMimeType.put("application/msword", listOf("doc", "dot"))
        extByMimeType.put("application/mxf", listOf("mxf"))
        extByMimeType.put("application/octet-stream", listOf("bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy"))
        extByMimeType.put("application/oda", listOf("oda"))
        extByMimeType.put("application/oebps-package+xml", listOf("opf"))
        extByMimeType.put("application/ogg", listOf("ogx"))
        extByMimeType.put("application/omdoc+xml", listOf("omdoc"))
        extByMimeType.put("application/onenote", listOf("onetoc", "onetoc2", "onetmp", "onepkg"))
        extByMimeType.put("application/oxps", listOf("oxps"))
        extByMimeType.put("application/patch-ops-error+xml", listOf("xer"))
        extByMimeType.put("application/pdf", listOf("pdf"))
        extByMimeType.put("application/pgp-encrypted", listOf("pgp"))
        extByMimeType.put("application/pgp-signature", listOf("asc", "sig"))
        extByMimeType.put("application/pics-rules", listOf("prf"))
        extByMimeType.put("application/pkcs10", listOf("p10"))
        extByMimeType.put("application/pkcs7-mime", listOf("p7m", "p7c"))
        extByMimeType.put("application/pkcs7-signature", listOf("p7s"))
        extByMimeType.put("application/pkcs8", listOf("p8"))
        extByMimeType.put("application/pkix-attr-cert", listOf("ac"))
        extByMimeType.put("application/pkix-cert", listOf("cer"))
        extByMimeType.put("application/pkix-crl", listOf("crl"))
        extByMimeType.put("application/pkix-pkipath", listOf("pkipath"))
        extByMimeType.put("application/pkixcmp", listOf("pki"))
        extByMimeType.put("application/pls+xml", listOf("pls"))
        extByMimeType.put("application/postscript", listOf("ai", "eps", "ps"))
        extByMimeType.put("application/prs.cww", listOf("cww"))
        extByMimeType.put("application/pskc+xml", listOf("pskcxml"))
        extByMimeType.put("application/rdf+xml", listOf("rdf"))
        extByMimeType.put("application/reginfo+xml", listOf("rif"))
        extByMimeType.put("application/relax-ng-compact-syntax", listOf("rnc"))
        extByMimeType.put("application/resource-lists+xml", listOf("rl"))
        extByMimeType.put("application/resource-lists-diff+xml", listOf("rld"))
        extByMimeType.put("application/rls-services+xml", listOf("rs"))
        extByMimeType.put("application/rpki-ghostbusters", listOf("gbr"))
        extByMimeType.put("application/rpki-manifest", listOf("mft"))
        extByMimeType.put("application/rpki-roa", listOf("roa"))
        extByMimeType.put("application/rsd+xml", listOf("rsd"))
        extByMimeType.put("application/rss+xml", listOf("rss"))
        extByMimeType.put("application/rtf", listOf("rtf"))
        extByMimeType.put("application/sbml+xml", listOf("sbml"))
        extByMimeType.put("application/scvp-cv-request", listOf("scq"))
        extByMimeType.put("application/scvp-cv-response", listOf("scs"))
        extByMimeType.put("application/scvp-vp-request", listOf("spq"))
        extByMimeType.put("application/scvp-vp-response", listOf("spp"))
        extByMimeType.put("application/sdp", listOf("sdp"))
        extByMimeType.put("application/set-payment-initiation", listOf("setpay"))
        extByMimeType.put("application/set-registration-initiation", listOf("setreg"))
        extByMimeType.put("application/shf+xml", listOf("shf"))
        extByMimeType.put("application/smil+xml", listOf("smi", "smil"))
        extByMimeType.put("application/sparql-query", listOf("rq"))
        extByMimeType.put("application/sparql-results+xml", listOf("srx"))
        extByMimeType.put("application/srgs", listOf("gram"))
        extByMimeType.put("application/srgs+xml", listOf("grxml"))
        extByMimeType.put("application/sru+xml", listOf("sru"))
        extByMimeType.put("application/ssdl+xml", listOf("ssdl"))
        extByMimeType.put("application/ssml+xml", listOf("ssml"))
        extByMimeType.put("application/tei+xml", listOf("tei", "teicorpus"))
        extByMimeType.put("application/thraud+xml", listOf("tfi"))
        extByMimeType.put("application/timestamped-data", listOf("tsd"))
        extByMimeType.put("application/vnd.3gpp.pic-bw-large", listOf("plb"))
        extByMimeType.put("application/vnd.3gpp.pic-bw-small", listOf("psb"))
        extByMimeType.put("application/vnd.3gpp.pic-bw-var", listOf("pvb"))
        extByMimeType.put("application/vnd.3gpp2.tcap", listOf("tcap"))
        extByMimeType.put("application/vnd.3m.post-it-notes", listOf("pwn"))
        extByMimeType.put("application/vnd.accpac.simply.aso", listOf("aso"))
        extByMimeType.put("application/vnd.accpac.simply.imp", listOf("imp"))
        extByMimeType.put("application/vnd.acucobol", listOf("acu"))
        extByMimeType.put("application/vnd.acucorp", listOf("atc", "acutc"))
        extByMimeType.put("application/vnd.adobe.air-application-installer-package+zip", listOf("air"))
        extByMimeType.put("application/vnd.adobe.formscentral.fcdt", listOf("fcdt"))
        extByMimeType.put("application/vnd.adobe.fxp", listOf("fxp", "fxpl"))
        extByMimeType.put("application/vnd.adobe.xdp+xml", listOf("xdp"))
        extByMimeType.put("application/vnd.adobe.xfdf", listOf("xfdf"))
        extByMimeType.put("application/vnd.ahead.space", listOf("ahead"))
        extByMimeType.put("application/vnd.airzip.filesecure.azf", listOf("azf"))
        extByMimeType.put("application/vnd.airzip.filesecure.azs", listOf("azs"))
        extByMimeType.put("application/vnd.amazon.ebook", listOf("azw"))
        extByMimeType.put("application/vnd.americandynamics.acc", listOf("acc"))
        extByMimeType.put("application/vnd.amiga.ami", listOf("ami"))
        extByMimeType.put("application/vnd.android.package-archive", listOf("apk"))
        extByMimeType.put("application/vnd.anser-web-certificate-issue-initiation", listOf("cii"))
        extByMimeType.put("application/vnd.anser-web-funds-transfer-initiation", listOf("fti"))
        extByMimeType.put("application/vnd.antix.game-component", listOf("atx"))
        extByMimeType.put("application/vnd.apple.installer+xml", listOf("mpkg"))
        extByMimeType.put("application/vnd.apple.mpegurl", listOf("m3u8"))
        extByMimeType.put("application/vnd.aristanetworks.swi", listOf("swi"))
        extByMimeType.put("application/vnd.astraea-software.iota", listOf("iota"))
        extByMimeType.put("application/vnd.audiograph", listOf("aep"))
        extByMimeType.put("application/vnd.blueice.multipass", listOf("mpm"))
        extByMimeType.put("application/vnd.bmi", listOf("bmi"))
        extByMimeType.put("application/vnd.businessobjects", listOf("rep"))
        extByMimeType.put("application/vnd.chemdraw+xml", listOf("cdxml"))
        extByMimeType.put("application/vnd.chipnuts.karaoke-mmd", listOf("mmd"))
        extByMimeType.put("application/vnd.cinderella", listOf("cdy"))
        extByMimeType.put("application/vnd.claymore", listOf("cla"))
        extByMimeType.put("application/vnd.cloanto.rp9", listOf("rp9"))
        extByMimeType.put("application/vnd.clonk.c4group", listOf("c4g", "c4d", "c4f", "c4p", "c4u"))
        extByMimeType.put("application/vnd.cluetrust.cartomobile-config", listOf("c11amc"))
        extByMimeType.put("application/vnd.cluetrust.cartomobile-config-pkg", listOf("c11amz"))
        extByMimeType.put("application/vnd.commonspace", listOf("csp"))
        extByMimeType.put("application/vnd.contact.cmsg", listOf("cdbcmsg"))
        extByMimeType.put("application/vnd.cosmocaller", listOf("cmc"))
        extByMimeType.put("application/vnd.crick.clicker", listOf("clkx"))
        extByMimeType.put("application/vnd.crick.clicker.keyboard", listOf("clkk"))
        extByMimeType.put("application/vnd.crick.clicker.palette", listOf("clkp"))
        extByMimeType.put("application/vnd.crick.clicker.template", listOf("clkt"))
        extByMimeType.put("application/vnd.crick.clicker.wordbank", listOf("clkw"))
        extByMimeType.put("application/vnd.criticaltools.wbs+xml", listOf("wbs"))
        extByMimeType.put("application/vnd.ctc-posml", listOf("pml"))
        extByMimeType.put("application/vnd.cups-ppd", listOf("ppd"))
        extByMimeType.put("application/vnd.curl.car", listOf("car"))
        extByMimeType.put("application/vnd.curl.pcurl", listOf("pcurl"))
        extByMimeType.put("application/vnd.dart", listOf("dart"))
        extByMimeType.put("application/vnd.data-vision.rdz", listOf("rdz"))
        extByMimeType.put("application/vnd.dece.data", listOf("uvf", "uvvf", "uvd", "uvvd"))
        extByMimeType.put("application/vnd.dece.ttml+xml", listOf("uvt", "uvvt"))
        extByMimeType.put("application/vnd.dece.unspecified", listOf("uvx", "uvvx"))
        extByMimeType.put("application/vnd.dece.zip", listOf("uvz", "uvvz"))
        extByMimeType.put("application/vnd.denovo.fcselayout-link", listOf("fe_launch"))
        extByMimeType.put("application/vnd.dna", listOf("dna"))
        extByMimeType.put("application/vnd.dolby.mlp", listOf("mlp"))
        extByMimeType.put("application/vnd.dpgraph", listOf("dpg"))
        extByMimeType.put("application/vnd.dreamfactory", listOf("dfac"))
        extByMimeType.put("application/vnd.ds-keypoint", listOf("kpxx"))
        extByMimeType.put("application/vnd.dvb.ait", listOf("ait"))
        extByMimeType.put("application/vnd.dvb.service", listOf("svc"))
        extByMimeType.put("application/vnd.dynageo", listOf("geo"))
        extByMimeType.put("application/vnd.ecowin.chart", listOf("mag"))
        extByMimeType.put("application/vnd.enliven", listOf("nml"))
        extByMimeType.put("application/vnd.epson.esf", listOf("esf"))
        extByMimeType.put("application/vnd.epson.msf", listOf("msf"))
        extByMimeType.put("application/vnd.epson.quickanime", listOf("qam"))
        extByMimeType.put("application/vnd.epson.salt", listOf("slt"))
        extByMimeType.put("application/vnd.epson.ssf", listOf("ssf"))
        extByMimeType.put("application/vnd.eszigno3+xml", listOf("es3", "et3"))
        extByMimeType.put("application/vnd.ezpix-album", listOf("ez2"))
        extByMimeType.put("application/vnd.ezpix-package", listOf("ez3"))
        extByMimeType.put("application/vnd.fdf", listOf("fdf"))
        extByMimeType.put("application/vnd.fdsn.mseed", listOf("mseed"))
        extByMimeType.put("application/vnd.fdsn.seed", listOf("seed", "dataless"))
        extByMimeType.put("application/vnd.flographit", listOf("gph"))
        extByMimeType.put("application/vnd.fluxtime.clip", listOf("ftc"))
        extByMimeType.put("application/vnd.framemaker", listOf("fm", "frame", "maker", "book"))
        extByMimeType.put("application/vnd.frogans.fnc", listOf("fnc"))
        extByMimeType.put("application/vnd.frogans.ltf", listOf("ltf"))
        extByMimeType.put("application/vnd.fsc.weblaunch", listOf("fsc"))
        extByMimeType.put("application/vnd.fujitsu.oasys", listOf("oas"))
        extByMimeType.put("application/vnd.fujitsu.oasys2", listOf("oa2"))
        extByMimeType.put("application/vnd.fujitsu.oasys3", listOf("oa3"))
        extByMimeType.put("application/vnd.fujitsu.oasysgp", listOf("fg5"))
        extByMimeType.put("application/vnd.fujitsu.oasysprs", listOf("bh2"))
        extByMimeType.put("application/vnd.fujixerox.ddd", listOf("ddd"))
        extByMimeType.put("application/vnd.fujixerox.docuworks", listOf("xdw"))
        extByMimeType.put("application/vnd.fujixerox.docuworks.binder", listOf("xbd"))
        extByMimeType.put("application/vnd.fuzzysheet", listOf("fzs"))
        extByMimeType.put("application/vnd.genomatix.tuxedo", listOf("txd"))
        extByMimeType.put("application/vnd.geogebra.file", listOf("ggb"))
        extByMimeType.put("application/vnd.geogebra.tool", listOf("ggt"))
        extByMimeType.put("application/vnd.geometry-explorer", listOf("gex", "gre"))
        extByMimeType.put("application/vnd.geonext", listOf("gxt"))
        extByMimeType.put("application/vnd.geoplan", listOf("g2w"))
        extByMimeType.put("application/vnd.geospace", listOf("g3w"))
        extByMimeType.put("application/vnd.gmx", listOf("gmx"))
        extByMimeType.put("application/vnd.google-earth.kml+xml", listOf("kml"))
        extByMimeType.put("application/vnd.google-earth.kmz", listOf("kmz"))
        extByMimeType.put("application/vnd.grafeq", listOf("gqf", "gqs"))
        extByMimeType.put("application/vnd.groove-account", listOf("gac"))
        extByMimeType.put("application/vnd.groove-help", listOf("ghf"))
        extByMimeType.put("application/vnd.groove-identity-message", listOf("gim"))
        extByMimeType.put("application/vnd.groove-injector", listOf("grv"))
        extByMimeType.put("application/vnd.groove-tool-message", listOf("gtm"))
        extByMimeType.put("application/vnd.groove-tool-template", listOf("tpl"))
        extByMimeType.put("application/vnd.groove-vcard", listOf("vcg"))
        extByMimeType.put("application/vnd.hal+xml", listOf("hal"))
        extByMimeType.put("application/vnd.handheld-entertainment+xml", listOf("zmm"))
        extByMimeType.put("application/vnd.hbci", listOf("hbci"))
        extByMimeType.put("application/vnd.hhe.lesson-player", listOf("les"))
        extByMimeType.put("application/vnd.hp-hpgl", listOf("hpgl"))
        extByMimeType.put("application/vnd.hp-hpid", listOf("hpid"))
        extByMimeType.put("application/vnd.hp-hps", listOf("hps"))
        extByMimeType.put("application/vnd.hp-jlyt", listOf("jlt"))
        extByMimeType.put("application/vnd.hp-pcl", listOf("pcl"))
        extByMimeType.put("application/vnd.hp-pclxl", listOf("pclxl"))
        extByMimeType.put("application/vnd.hydrostatix.sof-data", listOf("sfd-hdstx"))
        extByMimeType.put("application/vnd.ibm.minipay", listOf("mpy"))
        extByMimeType.put("application/vnd.ibm.modcap", listOf("afp", "listafp", "list3820"))
        extByMimeType.put("application/vnd.ibm.rights-management", listOf("irm"))
        extByMimeType.put("application/vnd.ibm.secure-container", listOf("sc"))
        extByMimeType.put("application/vnd.iccprofile", listOf("icc", "icm"))
        extByMimeType.put("application/vnd.igloader", listOf("igl"))
        extByMimeType.put("application/vnd.immervision-ivp", listOf("ivp"))
        extByMimeType.put("application/vnd.immervision-ivu", listOf("ivu"))
        extByMimeType.put("application/vnd.insors.igm", listOf("igm"))
        extByMimeType.put("application/vnd.intercon.formnet", listOf("xpw", "xpx"))
        extByMimeType.put("application/vnd.intergeo", listOf("i2g"))
        extByMimeType.put("application/vnd.intu.qbo", listOf("qbo"))
        extByMimeType.put("application/vnd.intu.qfx", listOf("qfx"))
        extByMimeType.put("application/vnd.ipunplugged.rcprofile", listOf("rcprofile"))
        extByMimeType.put("application/vnd.irepository.package+xml", listOf("irp"))
        extByMimeType.put("application/vnd.is-xpr", listOf("xpr"))
        extByMimeType.put("application/vnd.isac.fcs", listOf("fcs"))
        extByMimeType.put("application/vnd.jam", listOf("jam"))
        extByMimeType.put("application/vnd.jcp.javame.midlet-rms", listOf("rms"))
        extByMimeType.put("application/vnd.jisp", listOf("jisp"))
        extByMimeType.put("application/vnd.joost.joda-archive", listOf("joda"))
        extByMimeType.put("application/vnd.kahootz", listOf("ktz", "ktr"))
        extByMimeType.put("application/vnd.kde.karbon", listOf("karbon"))
        extByMimeType.put("application/vnd.kde.kchart", listOf("chrt"))
        extByMimeType.put("application/vnd.kde.kformula", listOf("kfo"))
        extByMimeType.put("application/vnd.kde.kivio", listOf("flw"))
        extByMimeType.put("application/vnd.kde.kontour", listOf("kon"))
        extByMimeType.put("application/vnd.kde.kpresenter", listOf("kpr", "kpt"))
        extByMimeType.put("application/vnd.kde.kspread", listOf("ksp"))
        extByMimeType.put("application/vnd.kde.kword", listOf("kwd", "kwt"))
        extByMimeType.put("application/vnd.kenameaapp", listOf("htke"))
        extByMimeType.put("application/vnd.kidspiration", listOf("kia"))
        extByMimeType.put("application/vnd.kinar", listOf("kne", "knp"))
        extByMimeType.put("application/vnd.koan", listOf("skp", "skd", "skt", "skm"))
        extByMimeType.put("application/vnd.kodak-descriptor", listOf("sse"))
        extByMimeType.put("application/vnd.las.las+xml", listOf("lasxml"))
        extByMimeType.put("application/vnd.llamagraphics.life-balance.desktop", listOf("lbd"))
        extByMimeType.put("application/vnd.llamagraphics.life-balance.exchange+xml", listOf("lbe"))
        extByMimeType.put("application/vnd.lotus-1-2-3", listOf("123"))
        extByMimeType.put("application/vnd.lotus-approach", listOf("apr"))
        extByMimeType.put("application/vnd.lotus-freelance", listOf("pre"))
        extByMimeType.put("application/vnd.lotus-notes", listOf("nsf"))
        extByMimeType.put("application/vnd.lotus-organizer", listOf("org"))
        extByMimeType.put("application/vnd.lotus-screencam", listOf("scm"))
        extByMimeType.put("application/vnd.lotus-wordpro", listOf("lwp"))
        extByMimeType.put("application/vnd.macports.portpkg", listOf("portpkg"))
        extByMimeType.put("application/vnd.mcd", listOf("mcd"))
        extByMimeType.put("application/vnd.medcalcdata", listOf("mc1"))
        extByMimeType.put("application/vnd.mediastation.cdkey", listOf("cdkey"))
        extByMimeType.put("application/vnd.mfer", listOf("mwf"))
        extByMimeType.put("application/vnd.mfmp", listOf("mfm"))
        extByMimeType.put("application/vnd.micrografx.flo", listOf("flo"))
        extByMimeType.put("application/vnd.micrografx.igx", listOf("igx"))
        extByMimeType.put("application/vnd.mif", listOf("mif"))
        extByMimeType.put("application/vnd.mobius.daf", listOf("daf"))
        extByMimeType.put("application/vnd.mobius.dis", listOf("dis"))
        extByMimeType.put("application/vnd.mobius.mbk", listOf("mbk"))
        extByMimeType.put("application/vnd.mobius.mqy", listOf("mqy"))
        extByMimeType.put("application/vnd.mobius.msl", listOf("msl"))
        extByMimeType.put("application/vnd.mobius.plc", listOf("plc"))
        extByMimeType.put("application/vnd.mobius.txf", listOf("txf"))
        extByMimeType.put("application/vnd.mophun.application", listOf("mpn"))
        extByMimeType.put("application/vnd.mophun.certificate", listOf("mpc"))
        extByMimeType.put("application/vnd.mozilla.xul+xml", listOf("xul"))
        extByMimeType.put("application/vnd.ms-artgalry", listOf("cil"))
        extByMimeType.put("application/vnd.ms-cab-compressed", listOf("cab"))
        extByMimeType.put("application/vnd.ms-excel", listOf("xls", "xlm", "xla", "xlc", "xlt", "xlw"))
        extByMimeType.put("application/vnd.ms-excel.addin.macroenabled.12", listOf("xlam"))
        extByMimeType.put("application/vnd.ms-excel.sheet.binary.macroenabled.12", listOf("xlsb"))
        extByMimeType.put("application/vnd.ms-excel.sheet.macroenabled.12", listOf("xlsm"))
        extByMimeType.put("application/vnd.ms-excel.template.macroenabled.12", listOf("xltm"))
        extByMimeType.put("application/vnd.ms-fontobject", listOf("eot"))
        extByMimeType.put("application/vnd.ms-htmlhelp", listOf("chm"))
        extByMimeType.put("application/vnd.ms-ims", listOf("ims"))
        extByMimeType.put("application/vnd.ms-lrm", listOf("lrm"))
        extByMimeType.put("application/vnd.ms-officetheme", listOf("thmx"))
        extByMimeType.put("application/vnd.ms-pki.seccat", listOf("cat"))
        extByMimeType.put("application/vnd.ms-pki.stl", listOf("stl"))
        extByMimeType.put("application/vnd.ms-powerpoint", listOf("ppt", "pps", "pot"))
        extByMimeType.put("application/vnd.ms-powerpoint.addin.macroenabled.12", listOf("ppam"))
        extByMimeType.put("application/vnd.ms-powerpoint.presentation.macroenabled.12", listOf("pptm"))
        extByMimeType.put("application/vnd.ms-powerpoint.slide.macroenabled.12", listOf("sldm"))
        extByMimeType.put("application/vnd.ms-powerpoint.slideshow.macroenabled.12", listOf("ppsm"))
        extByMimeType.put("application/vnd.ms-powerpoint.template.macroenabled.12", listOf("potm"))
        extByMimeType.put("application/vnd.ms-project", listOf("mpp", "mpt"))
        extByMimeType.put("application/vnd.ms-word.document.macroenabled.12", listOf("docm"))
        extByMimeType.put("application/vnd.ms-word.template.macroenabled.12", listOf("dotm"))
        extByMimeType.put("application/vnd.ms-works", listOf("wps", "wks", "wcm", "wdb"))
        extByMimeType.put("application/vnd.ms-wpl", listOf("wpl"))
        extByMimeType.put("application/vnd.ms-xpsdocument", listOf("xps"))
        extByMimeType.put("application/vnd.mseq", listOf("mseq"))
        extByMimeType.put("application/vnd.musician", listOf("mus"))
        extByMimeType.put("application/vnd.muvee.style", listOf("msty"))
        extByMimeType.put("application/vnd.mynfc", listOf("taglet"))
        extByMimeType.put("application/vnd.neurolanguage.nlu", listOf("nlu"))
        extByMimeType.put("application/vnd.nitf", listOf("ntf", "nitf"))
        extByMimeType.put("application/vnd.noblenet-directory", listOf("nnd"))
        extByMimeType.put("application/vnd.noblenet-sealer", listOf("nns"))
        extByMimeType.put("application/vnd.noblenet-web", listOf("nnw"))
        extByMimeType.put("application/vnd.nokia.n-gage.data", listOf("ngdat"))
        extByMimeType.put("application/vnd.nokia.n-gage.symbian.install", listOf("n-gage"))
        extByMimeType.put("application/vnd.nokia.radio-preset", listOf("rpst"))
        extByMimeType.put("application/vnd.nokia.radio-presets", listOf("rpss"))
        extByMimeType.put("application/vnd.novadigm.edm", listOf("edm"))
        extByMimeType.put("application/vnd.novadigm.edx", listOf("edx"))
        extByMimeType.put("application/vnd.novadigm.ext", listOf("ext"))
        extByMimeType.put("application/vnd.oasis.opendocument.chart", listOf("odc"))
        extByMimeType.put("application/vnd.oasis.opendocument.chart-template", listOf("otc"))
        extByMimeType.put("application/vnd.oasis.opendocument.database", listOf("odb"))
        extByMimeType.put("application/vnd.oasis.opendocument.formula", listOf("odf"))
        extByMimeType.put("application/vnd.oasis.opendocument.formula-template", listOf("odft"))
        extByMimeType.put("application/vnd.oasis.opendocument.graphics", listOf("odg"))
        extByMimeType.put("application/vnd.oasis.opendocument.graphics-template", listOf("otg"))
        extByMimeType.put("application/vnd.oasis.opendocument.image", listOf("odi"))
        extByMimeType.put("application/vnd.oasis.opendocument.image-template", listOf("oti"))
        extByMimeType.put("application/vnd.oasis.opendocument.presentation", listOf("odp"))
        extByMimeType.put("application/vnd.oasis.opendocument.presentation-template", listOf("otp"))
        extByMimeType.put("application/vnd.oasis.opendocument.spreadsheet", listOf("ods"))
        extByMimeType.put("application/vnd.oasis.opendocument.spreadsheet-template", listOf("ots"))
        extByMimeType.put("application/vnd.oasis.opendocument.text", listOf("odt"))
        extByMimeType.put("application/vnd.oasis.opendocument.text-master", listOf("odm"))
        extByMimeType.put("application/vnd.oasis.opendocument.text-template", listOf("ott"))
        extByMimeType.put("application/vnd.oasis.opendocument.text-web", listOf("oth"))
        extByMimeType.put("application/vnd.olpc-sugar", listOf("xo"))
        extByMimeType.put("application/vnd.oma.dd2+xml", listOf("dd2"))
        extByMimeType.put("application/vnd.openofficeorg.extension", listOf("oxt"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.presentationml.presentation", listOf("pptx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.presentationml.slide", listOf("sldx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.presentationml.slideshow", listOf("ppsx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.presentationml.template", listOf("potx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", listOf("xlsx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.spreadsheetml.template", listOf("xltx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.wordprocessingml.document", listOf("docx"))
        extByMimeType.put("application/vnd.openxmlformats-officedocument.wordprocessingml.template", listOf("dotx"))
        extByMimeType.put("application/vnd.osgeo.mapguide.package", listOf("mgp"))
        extByMimeType.put("application/vnd.osgi.dp", listOf("dp"))
        extByMimeType.put("application/vnd.osgi.subsystem", listOf("esa"))
        extByMimeType.put("application/vnd.palm", listOf("pdb", "pqa", "oprc"))
        extByMimeType.put("application/vnd.pawaafile", listOf("paw"))
        extByMimeType.put("application/vnd.pg.format", listOf("str"))
        extByMimeType.put("application/vnd.pg.osasli", listOf("ei6"))
        extByMimeType.put("application/vnd.picsel", listOf("efif"))
        extByMimeType.put("application/vnd.pmi.widget", listOf("wg"))
        extByMimeType.put("application/vnd.pocketlearn", listOf("plf"))
        extByMimeType.put("application/vnd.powerbuilder6", listOf("pbd"))
        extByMimeType.put("application/vnd.previewsystems.box", listOf("box"))
        extByMimeType.put("application/vnd.proteus.magazine", listOf("mgz"))
        extByMimeType.put("application/vnd.publishare-delta-tree", listOf("qps"))
        extByMimeType.put("application/vnd.pvi.ptid1", listOf("ptid"))
        extByMimeType.put("application/vnd.quark.quarkxpress", listOf("qxd", "qxt", "qwd", "qwt", "qxl", "qxb"))
        extByMimeType.put("application/vnd.realvnc.bed", listOf("bed"))
        extByMimeType.put("application/vnd.recordare.musicxml", listOf("mxl"))
        extByMimeType.put("application/vnd.recordare.musicxml+xml", listOf("musicxml"))
        extByMimeType.put("application/vnd.rig.cryptonote", listOf("cryptonote"))
        extByMimeType.put("application/vnd.rim.cod", listOf("cod"))
        extByMimeType.put("application/vnd.rn-realmedia", listOf("rm"))
        extByMimeType.put("application/vnd.rn-realmedia-vbr", listOf("rmvb"))
        extByMimeType.put("application/vnd.route66.link66+xml", listOf("link66"))
        extByMimeType.put("application/vnd.sailingtracker.track", listOf("st"))
        extByMimeType.put("application/vnd.seemail", listOf("see"))
        extByMimeType.put("application/vnd.sema", listOf("sema"))
        extByMimeType.put("application/vnd.semd", listOf("semd"))
        extByMimeType.put("application/vnd.semf", listOf("semf"))
        extByMimeType.put("application/vnd.shana.informed.formdata", listOf("ifm"))
        extByMimeType.put("application/vnd.shana.informed.formtemplate", listOf("itp"))
        extByMimeType.put("application/vnd.shana.informed.interchange", listOf("iif"))
        extByMimeType.put("application/vnd.shana.informed.package", listOf("ipk"))
        extByMimeType.put("application/vnd.simtech-mindmapper", listOf("twd", "twds"))
        extByMimeType.put("application/vnd.smaf", listOf("mmf"))
        extByMimeType.put("application/vnd.smart.teacher", listOf("teacher"))
        extByMimeType.put("application/vnd.solent.sdkm+xml", listOf("sdkm", "sdkd"))
        extByMimeType.put("application/vnd.spotfire.dxp", listOf("dxp"))
        extByMimeType.put("application/vnd.spotfire.sfs", listOf("sfs"))
        extByMimeType.put("application/vnd.stardivision.calc", listOf("sdc"))
        extByMimeType.put("application/vnd.stardivision.draw", listOf("sda"))
        extByMimeType.put("application/vnd.stardivision.impress", listOf("sdd"))
        extByMimeType.put("application/vnd.stardivision.math", listOf("smf"))
        extByMimeType.put("application/vnd.stardivision.writer", listOf("sdw", "vor"))
        extByMimeType.put("application/vnd.stardivision.writer-global", listOf("sgl"))
        extByMimeType.put("application/vnd.stepmania.package", listOf("smzip"))
        extByMimeType.put("application/vnd.stepmania.stepchart", listOf("sm"))
        extByMimeType.put("application/vnd.sun.xml.calc", listOf("sxc"))
        extByMimeType.put("application/vnd.sun.xml.calc.template", listOf("stc"))
        extByMimeType.put("application/vnd.sun.xml.draw", listOf("sxd"))
        extByMimeType.put("application/vnd.sun.xml.draw.template", listOf("std"))
        extByMimeType.put("application/vnd.sun.xml.impress", listOf("sxi"))
        extByMimeType.put("application/vnd.sun.xml.impress.template", listOf("sti"))
        extByMimeType.put("application/vnd.sun.xml.math", listOf("sxm"))
        extByMimeType.put("application/vnd.sun.xml.writer", listOf("sxw"))
        extByMimeType.put("application/vnd.sun.xml.writer.global", listOf("sxg"))
        extByMimeType.put("application/vnd.sun.xml.writer.template", listOf("stw"))
        extByMimeType.put("application/vnd.sus-calendar", listOf("sus", "susp"))
        extByMimeType.put("application/vnd.svd", listOf("svd"))
        extByMimeType.put("application/vnd.symbian.install", listOf("sis", "sisx"))
        extByMimeType.put("application/vnd.syncml+xml", listOf("xsm"))
        extByMimeType.put("application/vnd.syncml.dm+wbxml", listOf("bdm"))
        extByMimeType.put("application/vnd.syncml.dm+xml", listOf("xdm"))
        extByMimeType.put("application/vnd.tao.intent-module-archive", listOf("tao"))
        extByMimeType.put("application/vnd.tcpdump.pcap", listOf("pcap", "cap", "dmp"))
        extByMimeType.put("application/vnd.tmobile-livetv", listOf("tmo"))
        extByMimeType.put("application/vnd.trid.tpt", listOf("tpt"))
        extByMimeType.put("application/vnd.triscape.mxs", listOf("mxs"))
        extByMimeType.put("application/vnd.trueapp", listOf("tra"))
        extByMimeType.put("application/vnd.ufdl", listOf("ufd", "ufdl"))
        extByMimeType.put("application/vnd.uiq.theme", listOf("utz"))
        extByMimeType.put("application/vnd.umajin", listOf("umj"))
        extByMimeType.put("application/vnd.unity", listOf("unityweb"))
        extByMimeType.put("application/vnd.uoml+xml", listOf("uoml"))
        extByMimeType.put("application/vnd.vcx", listOf("vcx"))
        extByMimeType.put("application/vnd.visio", listOf("vsd", "vst", "vss", "vsw"))
        extByMimeType.put("application/vnd.visionary", listOf("vis"))
        extByMimeType.put("application/vnd.vsf", listOf("vsf"))
        extByMimeType.put("application/vnd.wap.wbxml", listOf("wbxml"))
        extByMimeType.put("application/vnd.wap.wmlc", listOf("wmlc"))
        extByMimeType.put("application/vnd.wap.wmlscriptc", listOf("wmlsc"))
        extByMimeType.put("application/vnd.webturbo", listOf("wtb"))
        extByMimeType.put("application/vnd.wolfram.player", listOf("nbp"))
        extByMimeType.put("application/vnd.wordperfect", listOf("wpd"))
        extByMimeType.put("application/vnd.wqd", listOf("wqd"))
        extByMimeType.put("application/vnd.wt.stf", listOf("stf"))
        extByMimeType.put("application/vnd.xara", listOf("xar"))
        extByMimeType.put("application/vnd.xfdl", listOf("xfdl"))
        extByMimeType.put("application/vnd.yamaha.hv-dic", listOf("hvd"))
        extByMimeType.put("application/vnd.yamaha.hv-script", listOf("hvs"))
        extByMimeType.put("application/vnd.yamaha.hv-voice", listOf("hvp"))
        extByMimeType.put("application/vnd.yamaha.openscoreformat", listOf("osf"))
        extByMimeType.put("application/vnd.yamaha.openscoreformat.osfpvg+xml", listOf("osfpvg"))
        extByMimeType.put("application/vnd.yamaha.smaf-audio", listOf("saf"))
        extByMimeType.put("application/vnd.yamaha.smaf-phrase", listOf("spf"))
        extByMimeType.put("application/vnd.yellowriver-custom-menu", listOf("cmp"))
        extByMimeType.put("application/vnd.zul", listOf("zir", "zirz"))
        extByMimeType.put("application/vnd.zzazz.deck+xml", listOf("zaz"))
        extByMimeType.put("application/voicexml+xml", listOf("vxml"))
        extByMimeType.put("application/widget", listOf("wgt"))
        extByMimeType.put("application/winhlp", listOf("hlp"))
        extByMimeType.put("application/wsdl+xml", listOf("wsdl"))
        extByMimeType.put("application/wspolicy+xml", listOf("wspolicy"))
        extByMimeType.put("application/x-7z-compressed", listOf("7z"))
        extByMimeType.put("application/x-abiword", listOf("abw"))
        extByMimeType.put("application/x-ace-compressed", listOf("ace"))
        extByMimeType.put("application/x-apple-diskimage", listOf("dmg"))
        extByMimeType.put("application/x-authorware-bin", listOf("aab", "x32", "u32", "vox"))
        extByMimeType.put("application/x-authorware-map", listOf("aam"))
        extByMimeType.put("application/x-authorware-seg", listOf("aas"))
        extByMimeType.put("application/x-bcpio", listOf("bcpio"))
        extByMimeType.put("application/x-bittorrent", listOf("torrent"))
        extByMimeType.put("application/x-blorb", listOf("blb", "blorb"))
        extByMimeType.put("application/x-bzip", listOf("bz"))
        extByMimeType.put("application/x-bzip2", listOf("bz2", "boz"))
        extByMimeType.put("application/x-cbr", listOf("cbr", "cba", "cbt", "cbz", "cb7"))
        extByMimeType.put("application/x-cdlink", listOf("vcd"))
        extByMimeType.put("application/x-cfs-compressed", listOf("cfs"))
        extByMimeType.put("application/x-chat", listOf("chat"))
        extByMimeType.put("application/x-chess-pgn", listOf("pgn"))
        extByMimeType.put("application/x-conference", listOf("nsc"))
        extByMimeType.put("application/x-cpio", listOf("cpio"))
        extByMimeType.put("application/x-csh", listOf("csh"))
        extByMimeType.put("application/x-debian-package", listOf("deb", "udeb"))
        extByMimeType.put("application/x-dgc-compressed", listOf("dgc"))
        extByMimeType.put("application/x-director", listOf("dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"))
        extByMimeType.put("application/x-doom", listOf("wad"))
        extByMimeType.put("application/x-dtbncx+xml", listOf("ncx"))
        extByMimeType.put("application/x-dtbook+xml", listOf("dtb"))
        extByMimeType.put("application/x-dtbresource+xml", listOf("res"))
        extByMimeType.put("application/x-dvi", listOf("dvi"))
        extByMimeType.put("application/x-envoy", listOf("evy"))
        extByMimeType.put("application/x-eva", listOf("eva"))
        extByMimeType.put("application/x-font-bdf", listOf("bdf"))
        extByMimeType.put("application/x-font-ghostscript", listOf("gsf"))
        extByMimeType.put("application/x-font-linux-psf", listOf("psf"))
        extByMimeType.put("application/x-font-otf", listOf("otf"))
        extByMimeType.put("application/x-font-pcf", listOf("pcf"))
        extByMimeType.put("application/x-font-snf", listOf("snf"))
        extByMimeType.put("application/x-font-ttf", listOf("ttf", "ttc"))
        extByMimeType.put("application/x-font-type1", listOf("pfa", "pfb", "pfm", "afm"))
        extByMimeType.put("application/x-font-woff", listOf("woff"))
        extByMimeType.put("application/x-freearc", listOf("arc"))
        extByMimeType.put("application/x-futuresplash", listOf("spl"))
        extByMimeType.put("application/x-gca-compressed", listOf("gca"))
        extByMimeType.put("application/x-glulx", listOf("ulx"))
        extByMimeType.put("application/x-gnumeric", listOf("gnumeric"))
        extByMimeType.put("application/x-gramps-xml", listOf("gramps"))
        extByMimeType.put("application/x-gtar", listOf("gtar"))
        extByMimeType.put("application/x-hdf", listOf("hdf"))
        extByMimeType.put("application/x-install-instructions", listOf("install"))
        extByMimeType.put("application/x-iso9660-image", listOf("iso"))
        extByMimeType.put("application/x-java-jnlp-file", listOf("jnlp"))
        extByMimeType.put("application/x-latex", listOf("latex"))
        extByMimeType.put("application/x-lzh-compressed", listOf("lzh", "lha"))
        extByMimeType.put("application/x-mie", listOf("mie"))
        extByMimeType.put("application/x-mobipocket-ebook", listOf("prc", "mobi"))
        extByMimeType.put("application/x-ms-application", listOf("application"))
        extByMimeType.put("application/x-ms-shortcut", listOf("lnk"))
        extByMimeType.put("application/x-ms-wmd", listOf("wmd"))
        extByMimeType.put("#/x-ms-wmz", listOf("wmz"))
        extByMimeType.put("application/x-ms-xbap", listOf("xbap"))
        extByMimeType.put("application/x-msaccess", listOf("mdb"))
        extByMimeType.put("application/x-msbinder", listOf("obd"))
        extByMimeType.put("application/x-mscardfile", listOf("crd"))
        extByMimeType.put("application/x-msclip", listOf("clp"))
        extByMimeType.put("application/x-msdownload", listOf("exe", "dll", "com", "bat", "msi"))
        extByMimeType.put("application/x-msmediaview", listOf("mvb", "m13", "m14"))
        extByMimeType.put("application/x-msmetafile", listOf("wmf", "wmz", "emf", "emz"))
        extByMimeType.put("application/x-msmoney", listOf("mny"))
        extByMimeType.put("application/x-mspublisher", listOf("pub"))
        extByMimeType.put("application/x-msschedule", listOf("scd"))
        extByMimeType.put("application/x-msterminal", listOf("trm"))
        extByMimeType.put("application/x-mswrite", listOf("wri"))
        extByMimeType.put("application/x-netcdf", listOf("nc", "cdf"))
        extByMimeType.put("application/x-nzb", listOf("nzb"))
        extByMimeType.put("application/x-pkcs12", listOf("p12", "pfx"))
        extByMimeType.put("application/x-pkcs7-certificates", listOf("p7b", "spc"))
        extByMimeType.put("application/x-pkcs7-certreqresp", listOf("p7r"))
        extByMimeType.put("application/x-rar-compressed", listOf("rar"))
        extByMimeType.put("application/x-research-info-systems", listOf("ris"))
        extByMimeType.put("application/x-sh", listOf("sh"))
        extByMimeType.put("application/x-shar", listOf("shar"))
        extByMimeType.put("application/x-shockwave-flash", listOf("swf"))
        extByMimeType.put("application/x-silverlight-app", listOf("xap"))
        extByMimeType.put("application/x-sql", listOf("sql"))
        extByMimeType.put("application/x-stuffit", listOf("sit"))
        extByMimeType.put("application/x-stuffitx", listOf("sitx"))
        extByMimeType.put("application/x-subrip", listOf("srt"))
        extByMimeType.put("application/x-sv4cpio", listOf("sv4cpio"))
        extByMimeType.put("application/x-sv4crc", listOf("sv4crc"))
        extByMimeType.put("application/x-t3vm-image", listOf("t3"))
        extByMimeType.put("application/x-tads", listOf("gam"))
        extByMimeType.put("application/x-tar", listOf("tar"))
        extByMimeType.put("application/x-tcl", listOf("tcl"))
        extByMimeType.put("application/x-tex", listOf("tex"))
        extByMimeType.put("application/x-tex-tfm", listOf("tfm"))
        extByMimeType.put("application/x-texinfo", listOf("texinfo", "texi"))
        extByMimeType.put("application/x-tgif", listOf("obj"))
        extByMimeType.put("application/x-ustar", listOf("ustar"))
        extByMimeType.put("application/x-wais-source", listOf("src"))
        extByMimeType.put("application/x-x509-ca-cert", listOf("der", "crt"))
        extByMimeType.put("application/x-xfig", listOf("fig"))
        extByMimeType.put("application/x-xliff+xml", listOf("xlf"))
        extByMimeType.put("application/x-xpinstall", listOf("xpi"))
        extByMimeType.put("application/x-xz", listOf("xz"))
        extByMimeType.put("application/x-zmachine", listOf("z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"))
        extByMimeType.put("application/xaml+xml", listOf("xaml"))
        extByMimeType.put("application/xcap-diff+xml", listOf("xdf"))
        extByMimeType.put("application/xenc+xml", listOf("xenc"))
        extByMimeType.put("application/xhtml+xml", listOf("xhtml", "xht"))
        extByMimeType.put("application/xml", listOf("xml", "xsl"))
        extByMimeType.put("application/xml-dtd", listOf("dtd"))
        extByMimeType.put("application/xop+xml", listOf("xop"))
        extByMimeType.put("application/xproc+xml", listOf("xpl"))
        extByMimeType.put("application/xslt+xml", listOf("xslt"))
        extByMimeType.put("application/xspf+xml", listOf("xspf"))
        extByMimeType.put("application/xv+xml", listOf("mxml", "xhvml", "xvml", "xvm"))
        extByMimeType.put("application/yang", listOf("yang"))
        extByMimeType.put("application/yin+xml", listOf("yin"))
        extByMimeType.put("application/zip", listOf("zip"))
        extByMimeType.put("audio/adpcm", listOf("adp"))
        extByMimeType.put("audio/basic", listOf("au", "snd"))
        extByMimeType.put("audio/midi", listOf("mid", "midi", "kar", "rmi"))
        extByMimeType.put("audio/mp4", listOf("mp4a"))
        extByMimeType.put("audio/mpeg", listOf("mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"))
        extByMimeType.put("audio/ogg", listOf("oga", "ogg", "spx"))
        extByMimeType.put("audio/s3m", listOf("s3m"))
        extByMimeType.put("audio/silk", listOf("sil"))
        extByMimeType.put("audio/vnd.dece.audio", listOf("uva", "uvva"))
        extByMimeType.put("audio/vnd.digital-winds", listOf("eol"))
        extByMimeType.put("audio/vnd.dra", listOf("dra"))
        extByMimeType.put("audio/vnd.dts", listOf("dts"))
        extByMimeType.put("audio/vnd.dts.hd", listOf("dtshd"))
        extByMimeType.put("audio/vnd.lucent.voice", listOf("lvp"))
        extByMimeType.put("audio/vnd.ms-playready.media.pya", listOf("pya"))
        extByMimeType.put("audio/vnd.nuera.ecelp4800", listOf("ecelp4800"))
        extByMimeType.put("audio/vnd.nuera.ecelp7470", listOf("ecelp7470"))
        extByMimeType.put("audio/vnd.nuera.ecelp9600", listOf("ecelp9600"))
        extByMimeType.put("audio/vnd.rip", listOf("rip"))
        extByMimeType.put("audio/webm", listOf("weba"))
        extByMimeType.put("audio/x-aac", listOf("aac"))
        extByMimeType.put("audio/x-aiff", listOf("aif", "aiff", "aifc"))
        extByMimeType.put("audio/x-caf", listOf("caf"))
        extByMimeType.put("audio/x-flac", listOf("flac"))
        extByMimeType.put("audio/x-matroska", listOf("mka"))
        extByMimeType.put("audio/x-mpegurl", listOf("m3u"))
        extByMimeType.put("audio/x-ms-wax", listOf("wax"))
        extByMimeType.put("audio/x-ms-wma", listOf("wma"))
        extByMimeType.put("audio/x-pn-realaudio", listOf("ram", "ra"))
        extByMimeType.put("audio/x-pn-realaudio-plugin", listOf("rmp"))
        extByMimeType.put("audio/x-wav", listOf("wav"))
        extByMimeType.put("audio/xm", listOf("xm"))
        extByMimeType.put("chemical/x-cdx", listOf("cdx"))
        extByMimeType.put("chemical/x-cif", listOf("cif"))
        extByMimeType.put("chemical/x-cmdf", listOf("cmdf"))
        extByMimeType.put("chemical/x-cml", listOf("cml"))
        extByMimeType.put("chemical/x-csml", listOf("csml"))
        extByMimeType.put("chemical/x-xyz", listOf("xyz"))
        extByMimeType.put("image/bmp", listOf("bmp"))
        extByMimeType.put("image/cgm", listOf("cgm"))
        extByMimeType.put("image/g3fax", listOf("g3"))
        extByMimeType.put("image/gif", listOf("gif"))
        extByMimeType.put("image/ief", listOf("ief"))
        extByMimeType.put("image/jpeg", listOf("jpeg", "jpg", "jpe"))
        extByMimeType.put("image/ktx", listOf("ktx"))
        extByMimeType.put("image/png", listOf("png"))
        extByMimeType.put("image/prs.btif", listOf("btif"))
        extByMimeType.put("image/sgi", listOf("sgi"))
        extByMimeType.put("image/svg+xml", listOf("svg", "svgz"))
        extByMimeType.put("image/tiff", listOf("tiff", "tif"))
        extByMimeType.put("image/vnd.adobe.photoshop", listOf("psd"))
        extByMimeType.put("image/vnd.dece.graphic", listOf("uvi", "uvvi", "uvg", "uvvg"))
        extByMimeType.put("image/vnd.djvu", listOf("djvu", "djv"))
        extByMimeType.put("image/vnd.dwg", listOf("dwg"))
        extByMimeType.put("image/vnd.dxf", listOf("dxf"))
        extByMimeType.put("image/vnd.fastbidsheet", listOf("fbs"))
        extByMimeType.put("image/vnd.fpx", listOf("fpx"))
        extByMimeType.put("image/vnd.fst", listOf("fst"))
        extByMimeType.put("image/vnd.fujixerox.edmics-mmr", listOf("mmr"))
        extByMimeType.put("image/vnd.fujixerox.edmics-rlc", listOf("rlc"))
        extByMimeType.put("image/vnd.ms-modi", listOf("mdi"))
        extByMimeType.put("image/vnd.ms-photo", listOf("wdp"))
        extByMimeType.put("image/vnd.net-fpx", listOf("npx"))
        extByMimeType.put("image/vnd.wap.wbmp", listOf("wbmp"))
        extByMimeType.put("image/vnd.xiff", listOf("xif"))
        extByMimeType.put("image/webp", listOf("webp"))
        extByMimeType.put("image/x-3ds", listOf("3ds"))
        extByMimeType.put("image/x-cmu-raster", listOf("ras"))
        extByMimeType.put("image/x-cmx", listOf("cmx"))
        extByMimeType.put("image/x-freehand", listOf("fh", "fhc", "fh4", "fh5", "fh7"))
        extByMimeType.put("image/x-icon", listOf("ico"))
        extByMimeType.put("image/x-mrsid-image", listOf("sid"))
        extByMimeType.put("image/x-pcx", listOf("pcx"))
        extByMimeType.put("image/x-pict", listOf("pic", "pct"))
        extByMimeType.put("image/x-portable-anymap", listOf("pnm"))
        extByMimeType.put("image/x-portable-bitmap", listOf("pbm"))
        extByMimeType.put("image/x-portable-graymap", listOf("pgm"))
        extByMimeType.put("image/x-portable-pixmap", listOf("ppm"))
        extByMimeType.put("image/x-rgb", listOf("rgb"))
        extByMimeType.put("image/x-tga", listOf("tga"))
        extByMimeType.put("image/x-xbitmap", listOf("xbm"))
        extByMimeType.put("image/x-xpixmap", listOf("xpm"))
        extByMimeType.put("image/x-xwindowdump", listOf("xwd"))
        extByMimeType.put("message/rfc822", listOf("eml", "mime"))
        extByMimeType.put("model/iges", listOf("igs", "iges"))
        extByMimeType.put("model/mesh", listOf("msh", "mesh", "silo"))
        extByMimeType.put("model/vnd.collada+xml", listOf("dae"))
        extByMimeType.put("model/vnd.dwf", listOf("dwf"))
        extByMimeType.put("model/vnd.gdl", listOf("gdl"))
        extByMimeType.put("model/vnd.gtw", listOf("gtw"))
        extByMimeType.put("model/vnd.mts", listOf("mts"))
        extByMimeType.put("model/vnd.vtu", listOf("vtu"))
        extByMimeType.put("model/vrml", listOf("wrl", "vrml"))
        extByMimeType.put("model/x3d+binary", listOf("x3db", "x3dbz"))
        extByMimeType.put("model/x3d+vrml", listOf("x3dv", "x3dvz"))
        extByMimeType.put("model/x3d+xml", listOf("x3d", "x3dz"))
        extByMimeType.put("text/cache-manifest", listOf("appcache"))
        extByMimeType.put("text/calendar", listOf("ics", "ifb"))
        extByMimeType.put("text/css", listOf("css"))
        extByMimeType.put("text/csv", listOf("csv"))
        extByMimeType.put("text/html", listOf("html", "htm"))
        extByMimeType.put("text/n3", listOf("n3"))
        extByMimeType.put("text/plain", listOf("txt", "text", "conf", "def", "list", "log", "in"))
        extByMimeType.put("text/prs.lines.tag", listOf("dsc"))
        extByMimeType.put("text/richtext", listOf("rtx"))
        extByMimeType.put("text/sgml", listOf("sgml", "sgm"))
        extByMimeType.put("text/tab-separated-values", listOf("tsv"))
        extByMimeType.put("text/troff", listOf("t", "tr", "roff", "man", "me", "ms"))
        extByMimeType.put("text/turtle", listOf("ttl"))
        extByMimeType.put("text/uri-list", listOf("uri", "uris", "urls"))
        extByMimeType.put("text/vcard", listOf("vcard"))
        extByMimeType.put("text/vnd.curl", listOf("curl"))
        extByMimeType.put("text/vnd.curl.dcurl", listOf("dcurl"))
        extByMimeType.put("text/vnd.curl.scurl", listOf("scurl"))
        extByMimeType.put("text/vnd.curl.mcurl", listOf("mcurl"))
        extByMimeType.put("text/vnd.dvb.subtitle", listOf("sub"))
        extByMimeType.put("text/vnd.fly", listOf("fly"))
        extByMimeType.put("text/vnd.fmi.flexstor", listOf("flx"))
        extByMimeType.put("text/vnd.graphviz", listOf("gv"))
        extByMimeType.put("text/vnd.in3d.3dml", listOf("3dml"))
        extByMimeType.put("text/vnd.in3d.spot", listOf("spot"))
        extByMimeType.put("text/vnd.sun.j2me.app-descriptor", listOf("jad"))
        extByMimeType.put("text/vnd.wap.wml", listOf("wml"))
        extByMimeType.put("text/vnd.wap.wmlscript", listOf("wmls"))
        extByMimeType.put("text/x-asm", listOf("s", "asm"))
        extByMimeType.put("text/x-c", listOf("c", "cc", "cxx", "cpp", "h", "hh", "dic"))
        extByMimeType.put("text/x-fortran", listOf("f", "for", "f77", "f90"))
        extByMimeType.put("text/x-java-source", listOf("java"))
        extByMimeType.put("text/x-opml", listOf("opml"))
        extByMimeType.put("text/x-pascal", listOf("p", "pas"))
        extByMimeType.put("text/x-nfo", listOf("nfo"))
        extByMimeType.put("text/x-setext", listOf("etx"))
        extByMimeType.put("text/x-sfv", listOf("sfv"))
        extByMimeType.put("text/x-uuencode", listOf("uu"))
        extByMimeType.put("text/x-vcalendar", listOf("vcs"))
        extByMimeType.put("text/x-vcard", listOf("vcf"))
        extByMimeType.put("video/3gpp", listOf("3gp"))
        extByMimeType.put("video/3gpp2", listOf("3g2"))
        extByMimeType.put("video/h261", listOf("h261"))
        extByMimeType.put("video/h263", listOf("h263"))
        extByMimeType.put("video/h264", listOf("h264"))
        extByMimeType.put("video/jpeg", listOf("jpgv"))
        extByMimeType.put("video/jpm", listOf("jpm", "jpgm"))
        extByMimeType.put("video/mj2", listOf("mj2", "mjp2"))
        extByMimeType.put("video/mp4", listOf("mp4", "mp4v", "mpg4"))
        extByMimeType.put("video/mpeg", listOf("mpeg", "mpg", "mpe", "m1v", "m2v"))
        extByMimeType.put("video/ogg", listOf("ogv"))
        extByMimeType.put("video/quicktime", listOf("qt", "mov"))
        extByMimeType.put("video/vnd.dece.hd", listOf("uvh", "uvvh"))
        extByMimeType.put("video/vnd.dece.mobile", listOf("uvm", "uvvm"))
        extByMimeType.put("video/vnd.dece.pd", listOf("uvp", "uvvp"))
        extByMimeType.put("video/vnd.dece.sd", listOf("uvs", "uvvs"))
        extByMimeType.put("video/vnd.dece.video", listOf("uvv", "uvvv"))
        extByMimeType.put("video/vnd.dvb.file", listOf("dvb"))
        extByMimeType.put("video/vnd.fvt", listOf("fvt"))
        extByMimeType.put("video/vnd.mpegurl", listOf("mxu", "m4u"))
        extByMimeType.put("video/vnd.ms-playready.media.pyv", listOf("pyv"))
        extByMimeType.put("video/vnd.uvvu.mp4", listOf("uvu", "uvvu"))
        extByMimeType.put("video/vnd.vivo", listOf("viv"))
        extByMimeType.put("video/webm", listOf("webm"))
        extByMimeType.put("video/x-f4v", listOf("f4v"))
        extByMimeType.put("video/x-fli", listOf("fli"))
        extByMimeType.put("video/x-flv", listOf("flv"))
        extByMimeType.put("video/x-m4v", listOf("m4v"))
        extByMimeType.put("video/x-matroska", listOf("mkv", "mk3d", "mks"))
        extByMimeType.put("video/x-mng", listOf("mng"))
        extByMimeType.put("video/x-ms-asf", listOf("asf", "asx"))
        extByMimeType.put("video/x-ms-vob", listOf("vob"))
        extByMimeType.put("video/x-ms-wm", listOf("wm"))
        extByMimeType.put("video/x-ms-wmv", listOf("wmv"))
        extByMimeType.put("video/x-ms-wmx", listOf("wmx"))
        extByMimeType.put("video/x-ms-wvx", listOf("wvx"))
        extByMimeType.put("video/x-msvideo", listOf("avi"))
        extByMimeType.put("video/x-sgi-movie", listOf("movie"))
        extByMimeType.put("video/x-smv", listOf("smv"))
        extByMimeType.put("x-conference/x-cooltalk", listOf("ice"))

        extByMimeType.forEach { mime, exts ->
            exts.forEach { ext ->
                mimeTypeByExt.put(ext, mime)
            }
        }
    }

    fun getMimeTypeByExt(fileExt: CharSequence): String? {
        if (fileExt.startsWith('.')) {
            return mimeTypeByExt[fileExt.subSequence(1, fileExt.length)]
        }
        return mimeTypeByExt[fileExt]
    }

    fun getExtByMediaType(mimeType: CharSequence): String? {
        return getAllFileExtByMediaType(mimeType).firstOrNull()
    }

    fun getAllFileExtByMediaType(mimeType: CharSequence): List<String> {
        return extByMimeType[mimeType] ?: emptyList()
    }
}
